blank_issues_enabled: false
contact_links:
  - name: "Sílabo del curso"
    url: "https://drive.google.com/drive/folders/1TCtLaDMl8345bIuZpejLhrtGBcHTEOJb"
    about: "Accede al sílabo y al material oficial del curso."
